import imageAvatar from '../../../assets/sidebar/avatar.png';

export const dataTweet = [
    {
        photo: imageAvatar,
        name: "Elon Musk",
        star: true,
        nickname: "@elonmusk",
        posted: "14h",
        content: `Ordered “How to Scam” book months ago but still not arrived. Starting to think it could be … but no I'm sure it's coming soon.`,
        comments: 14.8,
        reposts: 15.8,
        likes: 40.5,
        views: 500,
    },
    {
        photo: imageAvatar,
        name: "Azamat Smagulov",
        star: false,
        nickname: "@azamat.smg",
        posted: "20h",
        content: `I'm the best FullStack Developer ever! NFT, React, Angular, Django, Spring and etc... I know everything!!!`,
        comments: 1054,
        reposts: 1990,
        likes: 357.9,
        views: 400.68,
    },
    {
        photo: imageAvatar,
        name: "Azamat Smagulov",
        star: false,
        nickname: "@azamat.smg",
        posted: "20h",
        content: `I'm the best FullStack Developer ever! NFT, React, Angular, Django, Spring and etc... I know everything!!!`,
        comments: 1054,
        reposts: 1990,
        likes: 357.9,
        views: 400.68,
    },
    {
        photo: imageAvatar,
        name: "Azamat Smagulov",
        star: false,
        nickname: "@azamat.smg",
        posted: "20h",
        content: `I'm the best FullStack Developer ever! NFT, React, Angular, Django, Spring and etc... I know everything!!!`,
        comments: 1054,
        reposts: 1990,
        likes: 357.9,
        views: 400.68,
    },
    {
        photo: imageAvatar,
        name: "Azamat Smagulov",
        star: true,
        nickname: "@azamat.smg",
        posted: "20h",
        content: `I'm the best FullStack Developer ever! NFT, React, Angular, Django, Spring and etc... I know everything!!!`,
        comments: 1054,
        reposts: 1990,
        likes: 357.9,
        views: 400.68,
    },
    {
        photo: imageAvatar,
        name: "Azamat Smagulov",
        star: false,
        nickname: "@azamat.smg",
        posted: "20h",
        content: `I'm the best FullStack Developer ever! NFT, React, Angular, Django, Spring and etc... I know everything!!!`,
        comments: 1054,
        reposts: 1990,
        likes: 357.9,
        views: 400.68,
    },
]